
/* LEFT MOTOR */

#define CONFIG_LEFT_MOTOR_PWM_PINA              9
#define CONFIG_LEFT_MOTOR_PINB                  10
#define CONFIG_LEFT_MOTOR_INITIAL_SPEED         50
#define CONFIG_LEFT_MOTOR_INITIAL_DIRECTION     0x1

/* RIGHT MOTOR */

#define CONFIG_RIGHT_MOTOR_PWM_PINA              11
#define CONFIG_RIGHT_MOTOR_PINB                  12
#define CONFIG_RIGHT_MOTOR_INITIAL_SPEED         50
#define CONFIG_RIGHT_MOTOR_INITIAL_DIRECTION     0x1

/* INFRARED SENSOR */

#define CONFIG_LINE_FOLLOW_SENSOR_RIGHT         A0
#define CONFIG_LINE_FOLLOW_ANALOG_CENTER_RIGHT  A1
#define CONFIG_LINE_FOLLOW_ANALOG_CENTER_LEFT   A2
#define CONFIG_LINE_FOLLOW_ANALOG_LEFT          A3
